<?php

namespace EpayZoneBundle\Repository;

/**
 * PaymentOptionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentOptionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
