<?php

namespace EpayZoneBundle\Repository;

/**
 * PaymentOptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentOptionRepository extends \Doctrine\ORM\EntityRepository
{
}
