epayzone_homepage:
    path:     /
    defaults: { _controller: EpayZoneBundle:Default:index }
    
epayzone_vendor_dashboard:
    path:    /vendor/dashboard
    defaults: { _controller: EpayZoneBundle:Default:vendorDashboard }
    
gentelella_page:
    path:    /page
    defaults: { _controller: EpayZoneBundle:Default:vendorDashboard }
    
admin_page:
    path:    /page
    defaults: { _controller: EpayZoneBundle:Default:vendorDashboard }
    
epayzone_dashboard:
    path:    /epayzone/dashboard
    defaults: { _controller: EpayZoneBundle:Default:epayZoneDashboard }
    
epayzone_transfer:
    path: /epayzone-transfer
    defaults: { _controller: EpayZoneBundle:Default:Services }

epayzone_service_category:
    path: /epayzone-service-category/{id}
    defaults: { _controller: EpayZoneBundle:Default:ServiceCategory }