services:
    epay_zone.password_reseting:
        class: EpayZoneBundle\EventListener\PasswordResettingListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }
            
    epay_zone.registration_sucess:
        class: EpayZoneBundle\EventListener\RegistrationListener
        arguments: ["@router"]
        tags:
            - { name: kernel.event_subscriber }

    epay_zone.admin.transaction:
        class: EpayZoneBundle\Admin\TransactionAdmin
        arguments: [~, EpayZoneBundle\Entity\Transaction, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Transaction }

    epay_zone.admin.region:
        class: EpayZoneBundle\Admin\RegionAdmin
        arguments: [~, EpayZoneBundle\Entity\Region, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Region }

    epay_zone.admin.payment_option:
        class: EpayZoneBundle\Admin\PaymentOptionAdmin
        arguments: [~, EpayZoneBundle\Entity\PaymentOption, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: PaymentOption }

    epay_zone.admin.payment_option_type:
        class: EpayZoneBundle\Admin\PaymentOptionTypeAdmin
        arguments: [~, EpayZoneBundle\Entity\PaymentOptionType, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: PaymentOptionType }

    epay_zone.admin.service:
        class: EpayZoneBundle\Admin\ServiceAdmin
        arguments: [~, EpayZoneBundle\Entity\Service, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: Service }

    epay_zone.admin.service_category:
        class: EpayZoneBundle\Admin\ServiceCategoryAdmin
        arguments: [~, EpayZoneBundle\Entity\ServiceCategory, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: ServiceCategory }

    epay_zone.admin.transaction_log:
        class: EpayZoneBundle\Admin\TransactionLogAdmin
        arguments: [~, EpayZoneBundle\Entity\TransactionLog, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Admin, label: TransactionLog }
